### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#13]
Has no suggestions while typing yet.
Suggestions only appear when "enter" pressed.

**Comment by bopjesvla** [comment]
Autocomplete is heavy

**Comment by bopjesvla** [comment]
on the hardware

**Comment by bopjesvla** [comment]
Nvm, we got this for free from the Folium update :)

**Comment by bopjesvla** [comment]
Just for reference, I meant that Nominatim wouldn't allow this because their servers would get strained, but Folium now allows Photon as a provider
