### ISSUE TITLE
Better metrics about spots

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#15]
may be a good idea not to calculate the average of waiting times for each spot, but to calculate the median to normalize extremes. don't know if this is possible and if you save all values on the database or just average and number of votes...

    It now simply returns an average from all saved waitingtimes, so that 15m + 5min + 4h returns 1h 27min.

**Comment by tillwenke** [comment]
apply rounding to times

**Comment by tillwenke** [comment]
Define "Rating"/Hitchability of a spot that also determines the spot color.
consider: waiting time, safety, shelter, ... ?!

**Comment by tillwenke** [comment]
Be more objective
eg. this doesnt seem like a 3/5
![image](https://user-images.githubusercontent.com/38500891/223704414-fa4ca1f8-70c3-40ba-997c-b899918ef0d6.png)

**Comment by tillwenke** [comment]
Introduce naming for spots?

**Comment by tillwenke** [comment]
new metric: if you got the ride through thumb/sign or asking people.

**Comment by bopjesvla** [comment]
too few reviews for this
