### ISSUE TITLE
Cluster points beyond country level

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#16]
Adjust spots/ bubble sizes so that the map is still visible. Right now they dominate the map so that countries/ cities cannot be found when not already familiar with the area

**Comment by bopjesvla** [comment]
Was this before or after the transparancy update?

**Comment by tillwenke** [comment]
Referring to this 
![image](https://github.com/bopjesvla/hitch/assets/38500891/bcd01a66-ce8c-46cc-b7be-71238cf1c903)

**Comment by bopjesvla** [comment]
Havent seen that in a while, those bubbles should merge into bigger bubbles

**Comment by bopjesvla** [comment]
I added all points to 1 cluster for now
