### ISSUE TITLE
Not able to write review of a spot

### ISSUE THREAD

**Issue by erug-the-creator** [bopjesvla/hitch#2]
Hey amazing website, but as a new user I wanted to make my first review and always got an error message.

![Screenshot_20230131_085630_Chrome.jpg](https://user-images.githubusercontent.com/62485917/215700264-d4e05cdd-81b0-4ff0-bac9-c9dcab34a76f.jpg)

![Screenshot_20230131_085637_Chrome.jpg](https://user-images.githubusercontent.com/62485917/215700243-08173d9a-6095-4857-ad62-3bd0c6532cce.jpg)

Maybe I also did something wrong.

However keep going and thanks for every effort.

**Comment by bopjesvla** [comment]
Can you leave a review now?

**Comment by erug-the-creator** [comment]
Yes thanks 🙌
