### ISSUE TITLE
Set more accurate new spots

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#22]

**Comment by tillwenke** [comment]
attach spots to closest road

**Comment by tillwenke** [comment]
move spots out of tunnels

**Comment by tillwenke** [comment]
... out of water
![image](https://user-images.githubusercontent.com/38500891/223705154-ba0fddd5-5d5c-41d1-8ee2-a46053ea2761.png)

**Comment by tillwenke** [comment]
delete if no road even close 
![image](https://user-images.githubusercontent.com/38500891/223706513-9a314b43-4a04-4bc0-98b1-89e2b6847c89.png)
(keep Greenland spot)

**Comment by tillwenke** [comment]
Somehow clearly indicate the road that you are waiting at ... which direction of the road.
Might be solved by destination marker.

**Comment by tillwenke** [comment]
"Map scale of visual interpretation affects precision of digitizing ground object; therefore, just fixing map scale could assure quality in a certain range." https://www.geospatialworld.net/article/crowdsourcing-for-urban-area-mapping/

**Comment by tillwenke** [comment]
ability to report wrong/ useless/ mergable spots

**Comment by tillwenke** [comment]
ability to add current position as spot.

**Comment by bopjesvla** [comment]
This seems more like a brainstorm than an issue :) there's always been an "add a spot" button
