### ISSUE TITLE
Link spots to hitchwiki descriptions

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#23]
[Hitchwiki](https://hitchwiki.org/en/Main_Page) provides descriptions of good hh spots for all mayor cities. although they often only provide a description of the spot. Linking it to actual locations would make sense. And the other way around mark spots as kinda "special" on the hitchmap.

**Comment by bopjesvla** [comment]
The way to go about this is to make place names clickable, but I'm skeptical about it being worth the effort

**Comment by tillwenke** [comment]
As an example I started with the Wiki -> Map links for Dresden https://hitchwiki.org/en/Dresden (not complete).
As I found people did this before (infrequently) and their links do not work anymore.

**Comment by tillwenke** [comment]
> The way to go about this is to make place names clickable, but I'm skeptical about it being worth the effort

There are users for sure who never saw the map and only the wiki. they would look for the spot on another online map either way.

**Comment by tillwenke** [comment]
One would have to somehow make these links persistent or crawl changed wiki sites frequently.

**Comment by guaka** [comment]
relates to https://github.com/Hitchwiki/hitchwiki/issues/209
