### ISSUE TITLE
Spot ID instead of coordinates in link

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#39]
...location might change while spot stays the same conceptually.

take inspiration from Google maps 

https://maps.app.goo.gl/niUdDXDworeHzA4d8

or OSM
https://www.openstreetmap.org/node/1960302247#map=19/49.47146/8.43970

**Comment by bopjesvla** [comment]
Don't think this'll often happen, bar a landslide. If a structure moves places, it'll probably be different for the purpose of hitchhiking. Even if a spot is moved, we'll probably still put up something at the old spot that references the new spot, so no dead links there
