### ISSUE TITLE
Data API and dump

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#41]
can we improve anything on this end?

**Comment by tillwenke** [comment]
suggest to provide a history of dumps with new dump each e.g. month

**Comment by tillwenke** [comment]
...prolly no api needed then

**Comment by bopjesvla** [comment]
The points table all has a date column, so it's trivial to retrieve all reviews before a certain date if that's what you're wondering about. In general, it's good to think about a use case before opening an issue, rather than looking at a part of the website and going, is there something here?
