### ISSUE TITLE
Collect link for spot to hitchwiki article of its region/city

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#43]

**Comment by tillwenke** [comment]
use community to generate links. similar to duplicates reporting

**Comment by tillwenke** [comment]
collect links to sections like https://hitchwiki.org/en/Dresden#Option_1

**Comment by bderui** [comment]
I'm not a fan of having too many report options. This seems like it'd be used even less than the duplicate report option, and the duplicate report option is not being used as much as I'd hoped

**Comment by tillwenke** [comment]
this is not reporting in a cleaning sense. 

I believe that combining wiki and our spot data is valuable. not least because there are people who are only aware of the wiki.

establishing those links from our side feels much easier to me.

in the end it just gives the people who want the chance to report (like me :) - others dont have to mind.
