### ISSUE TITLE
Move Footer to Menu

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#47]
Suggestion:
Github logo, Download symbol.
recent changes are not necessary imo.
leave the rest.

**Comment by bopjesvla** [comment]
As I said on Signal, I still think the footer should be moved to a menu

It's nice for people to see other people are also contributing to Hitchmap, it can seem a bit isolated because there's no chronology to the spots on the map

**Comment by tillwenke** [comment]
What is the canonical solution for this?
Is this leaflet or folium?

**Comment by tillwenke** [comment]
@bopjesvla how do you imagine the menu visually? eg like this https://www.dumpstermap.org/page/about

**Comment by tillwenke** [comment]
try https://github.com/Turbo87/leaflet-sidebar?tab=readme-ov-file
