### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#48]
or do we prefer conda environment.yaml?

**Comment by bopjesvla** [comment]
I added the folium version to the README, which I guess is the most important

I like the installation instructions as they are tbh

**Comment by tillwenke** [comment]
i d like to adhere to python best practices https://docs.python-guide.org/writing/structure/

**Comment by bopjesvla** [comment]
I doubt Hitchmap will ever be anything other than a monolith. If someone finds a use case where Hitchmap (the software, not the db) is included as a dependency, we can consider turning it into a module.
