### ISSUE TITLE
Move "report" options to the top

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#58]
I d rathe place it as a button up here 
![image](https://github.com/bopjesvla/hitch/assets/38500891/731ed0cb-f9f3-4667-b700-d3caff778c2e)

(... alongside one for "Report as to be deleted")

**Comment by bopjesvla** [comment]
Would you prefer it visually or to make mass reporting easier?

**Comment by tillwenke** [comment]
as misleading spots are one of the main issues on the map, I d give in more visibility up there. encouraging users to report and showcase that that we are highly aware of this problem.

**Comment by bopjesvla** [comment]
I have been underwhelmed by the number of reports we've received, but I'm not convinced visibility is stopping people from reporting things. Most duplicate spots only have 1 or 2 reviews, so the link is usually visible. Its current placement seems fair considering the length of the link.
