### ISSUE TITLE
Security - User authentication

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#7]
to prevent a spam of new hh spots.

oauth with [hitchwiki.org](http://hitchwiki.org/)
... tough hitchwiki has some problems with their user accounts.

**Comment by tillwenke** [comment]
Do we want to allow editing the map without account?
Different approaches out there.
https://mundraub.org/map no!
https://www.dumpstermap.org/page/about yes!

**Comment by tillwenke** [comment]
oauth via Trustroots ?!

**Comment by bopjesvla** [comment]
We never had spam
