### ISSUE TITLE
Voting mechanism for hitchwiki linking

### ISSUE THREAD

**Issue by tillwenke** [bopjesvla/hitch#88]
which link should be displayed if different links are reported for one spot. how many times should a spot be linked before the link is displayed?

**Comment by bopjesvla** [comment]
we aren't going to add complexity to this unless absolutely necessary. closing for now, we can reopen once this pops up

**Comment by bopjesvla** [comment]
> how many times should a spot be linked before the link is displayed?

once, this can be implemented already afaic
